import type { MapData } from '../types/map';
import { LOCATION_PRESETS } from '../data/sampleMapData';
import { recategorizeBuilding } from './mapProcessor';

/**
 * Bundled offline city maps.
 *
 * Generated by `scripts/fetch-maps.ts` (run on an internet-connected machine),
 * which writes ONE fully-processed MapData JSON per city to:
 *   src/data/maps/<presetId>.json
 *
 * Each file already contains the real OSM geometry AND the 16x16 DEM elevation
 * grid, so the same artifact serves both the starting-area street map and the
 * 3D game without any network access.
 *
 * We lazy-load via import.meta.glob so no city data is pulled into the JS
 * bundle until that city is actually selected, and the app keeps working
 * normally when the files are absent (falls back to the live Overpass fetch).
 */

const modules = import.meta.glob('../data/maps/*.json');

type ChunkManifest = {
  format: 'terminus-map-chunks-v1';
  base: string;
  chunks: Array<{ file: string; kind: 'buildings' | 'roads' | 'landuse' | 'resourceNodes'; count: number }>;
};

async function loadJson(key: string): Promise<unknown> {
  const loader = modules[key];
  return loader ? loader() : null;
}

async function loadMapModule(key: string): Promise<MapData | null> {
  const value = await loadJson(key) as { default?: unknown } | null;
  const data = value?.default;
  if (!data || typeof data !== 'object') return null;
  const manifest = data as Partial<ChunkManifest>;
  if (manifest.format !== 'terminus-map-chunks-v1' || !manifest.base || !manifest.chunks) {
    const map = data as MapData;
    if (map.buildings) {
      for (const b of map.buildings) {
        b.type = recategorizeBuilding(b);
      }
    }
    return map;
  }

  const baseKey = Object.keys(modules).find((candidate) => candidate.endsWith(`/${manifest.base}`));
  if (!baseKey) throw new Error(`Missing map base ${manifest.base}`);
  const baseModule = await loadJson(baseKey) as { default?: MapData };
  const map = baseModule.default;
  if (!map) throw new Error(`Invalid map base ${manifest.base}`);
  const result: MapData = { ...map, buildings: [], roads: [], landuse: [], resourceNodes: [] };
  for (const chunk of manifest.chunks) {
    const chunkKey = Object.keys(modules).find((candidate) => candidate.endsWith(`/${chunk.file}`));
    if (!chunkKey) throw new Error(`Missing map chunk ${chunk.file}`);
    const chunkModule = await loadJson(chunkKey) as { default?: unknown[] };
    const items = chunkModule.default ?? [];
    (result[chunk.kind] as unknown[]).push(...items);
  }

  // Re-categorize all buildings using enhanced classification heuristics so pre-baked maps
  // (e.g. Oxford, London) get their universities, schools, hospitals, etc. properly recognized.
  if (result.buildings && result.buildings.length > 0) {
    for (const b of result.buildings) {
      b.type = recategorizeBuilding(b);
    }
  }

  result.stats = {
    ...result.stats,
    buildingCount: result.buildings.length,
    roadCount: result.roads.length,
    resourceCount: {
      wood: result.resourceNodes.filter((node) => node.type === 'wood').length,
      metal: result.resourceNodes.filter((node) => node.type === 'metal').length,
      bricks: result.resourceNodes.filter((node) => node.type === 'bricks').length,
      total: result.resourceNodes.length,
    },
  };
  return result;
}

// Tolerance (~5.5km) when matching a clicked coordinate to a bundled preset.
const MATCH_TOLERANCE_DEG = 0.05;

/**
 * Returns the preset id whose coordinates are nearest to the given lat/lon, or
 * null if no curated city is close enough to have a bundled map.
 */
export function getBundledMapId(lat: number, lon: number): string | null {
  let bestId: string | null = null;
  let bestDist = MATCH_TOLERANCE_DEG;
  for (const p of LOCATION_PRESETS) {
    const d = Math.hypot(p.lat - lat, p.lon - lon);
    if (d < bestDist) {
      bestDist = d;
      bestId = p.id;
    }
  }
  return bestId;
}

/**
 * Direct lookup by preset ID (e.g., 'oxford', 'evesham', 'paris_cite', etc.)
 */
export async function getBundledMapById(id: string): Promise<MapData | null> {
  const cleanId = id.replace(/_dl$/, '');
  const key = Object.keys(modules).find((k) => k.endsWith(`/${cleanId}.json`));
  if (!key) return null;

  try {
    return await loadMapModule(key);
  } catch (err) {
    console.warn(`Bundled map load failed for ${cleanId}:`, err);
    return null;
  }
}

/**
 * Loads the bundled MapData for the city nearest the given coordinate, or null
 * if there is no matching file (e.g. a custom/un-curated location, or the data
 * has not been generated yet). Matching is by coordinate — not by radius — so a
 * bundled 900m dataset is used regardless of the placement's radius.
 */
export async function getBundledMapData(lat: number, lon: number): Promise<MapData | null> {
  const id = getBundledMapId(lat, lon);
  if (!id) return null;
  return getBundledMapById(id);
}
