import type { MapData } from '../types/map';
import { LOCATION_PRESETS } from '../data/sampleMapData';

/**
 * Bundled offline city maps.
 *
 * Generated by `scripts/fetch-maps.ts` (run on an internet-connected machine),
 * which writes ONE fully-processed MapData JSON per city to:
 *   src/data/maps/<presetId>.json
 *
 * Each file already contains the real OSM geometry AND the 16x16 DEM elevation
 * grid, so the same artifact serves both the starting-area street map and the
 * 3D game without any network access.
 *
 * We lazy-load via import.meta.glob so no city data is pulled into the JS
 * bundle until that city is actually selected, and the app keeps working
 * normally when the files are absent (falls back to the live Overpass fetch).
 */

const modules = import.meta.glob('../data/maps/*.json');

// Tolerance (~5.5km) when matching a clicked coordinate to a bundled preset.
const MATCH_TOLERANCE_DEG = 0.05;

/**
 * Returns the preset id whose coordinates are nearest to the given lat/lon, or
 * null if no curated city is close enough to have a bundled map.
 */
export function getBundledMapId(lat: number, lon: number): string | null {
  let bestId: string | null = null;
  let bestDist = MATCH_TOLERANCE_DEG;
  for (const p of LOCATION_PRESETS) {
    const d = Math.hypot(p.lat - lat, p.lon - lon);
    if (d < bestDist) {
      bestDist = d;
      bestId = p.id;
    }
  }
  return bestId;
}

/**
 * Direct lookup by preset ID (e.g., 'oxford', 'evesham', 'paris_cite', etc.)
 */
export async function getBundledMapById(id: string): Promise<MapData | null> {
  const cleanId = id.replace(/_dl$/, '');
  const key = Object.keys(modules).find((k) => k.endsWith(`/${cleanId}.json`));
  if (!key) return null;

  try {
    const mod = await modules[key]();
    return (mod as { default?: MapData }).default ?? null;
  } catch (err) {
    console.warn(`Bundled map load failed for ${cleanId}:`, err);
    return null;
  }
}

/**
 * Loads the bundled MapData for the city nearest the given coordinate, or null
 * if there is no matching file (e.g. a custom/un-curated location, or the data
 * has not been generated yet). Matching is by coordinate — not by radius — so a
 * bundled 900m dataset is used regardless of the placement's radius.
 */
export async function getBundledMapData(lat: number, lon: number): Promise<MapData | null> {
  const id = getBundledMapId(lat, lon);
  if (!id) return null;
  return getBundledMapById(id);
}
