export type ResearchBranch =
  | 'medicine'
  | 'communication'
  | 'chemistry'
  | 'arms'
  | 'construction'
  | 'food'
  | 'infection'
  | 'education';

export interface ResearchEffect {
  stat: string;
  value: string;
  description: string;
}

export interface ResearchNode {
  id: string;
  branch: ResearchBranch;
  tier: 1 | 2 | 3 | 4; // depth from the category root; drives the graph columns
  name: string;
  description: string;
  // How long an active project takes, measured in research-worker-seconds.
  // Effective real time = baseTimeSec / researchWorkers, so more researchers
  // assigned to Research Stations complete a project faster.
  baseTimeSec: number;
  // Research Point cost, charged from the colony's research-point pool on
  // completion (the green book currency).
  costRP: number;
  prerequisites: string[]; // Node IDs required before this node can be started
  unlockedBuildingTypeId?: string;
  effects: ResearchEffect[];
  categoryTag: string;
}

export interface ResearchTreeState {
  // "Research Points" currency generated by Research Stations. Charged when a
  // project completes. The green book badge shows your available amount.
  researchPoints: number;
  passiveRatePerSec: number;
  unlockedNodes: string[];
  // Currently active time-based project (one at a time, IFZ-style).
  activeResearchId: string | null;
  // Research-worker-seconds accumulated toward the active project.
  activeProgressSec: number;
}