/**
 * Surgical river/waterway patch for existing offline bundles.
 *
 * The 8km bundles were generated by fetch-maps.ts whose Overpass query was
 * missing `way["waterway"]` — so linear rivers (which OSM encodes as
 * waterway=river/stream/canal WAYS) never made it into the data, while ponds
 * and lakes (natural=water) did. This script fetches ONLY the water elements
 * for each curated city and merges the resulting river polygons into the
 * existing <id>.json without re-downloading buildings/roads/elevation.
 *
 * Run ON A MACHINE WITH INTERNET:
 *   npx tsx scripts/add-rivers.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { LOCATION_PRESETS } from '../src/data/sampleMapData';
import { processOsmData } from '../src/services/mapProcessor';
import type { RawOsmResponse } from '../src/services/osmFetcher';
import type { LanduseArea } from '../src/types/map';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '../src/data/maps');

const RADIUS = 4000;

const OVERPASS_ENDPOINTS = [
  'https://overpass-api.de/api/interpreter',
  'https://lz4.overpass-api.de/api/interpreter',
  'https://z.overpass-api.de/api/interpreter',
  'https://overpass.private.coffee/api/interpreter',
  'https://overpass.openstreetmap.ru/api/interpreter',
];

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function buildWaterQuery(lat: number, lon: number, radius: number): string {
  return `[out:json][timeout:300];
(
  way["waterway"](around:${radius},${lat},${lon});
  way["water"](around:${radius},${lat},${lon});
  way["natural"="water"](around:${radius},${lat},${lon});
  relation["waterway"](around:${radius},${lat},${lon});
  relation["water"](around:${radius},${lat},${lon});
  relation["natural"="water"](around:${radius},${lat},${lon});
);
out body;
>;
out skel qt;`;
}

async function fetchWater(lat: number, lon: number): Promise<RawOsmResponse> {
  const query = buildWaterQuery(lat, lon, RADIUS);
  let lastError: Error | null = null;

  for (const endpoint of OVERPASS_ENDPOINTS) {
    for (let attempt = 1; attempt <= 3; attempt++) {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort('timeout'), 120_000);
      try {
        const res = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            Accept: 'application/json',
            'User-Agent': 'TERMINUS-water-patch/1.0 (one-time river merge)',
          },
          body: 'data=' + encodeURIComponent(query),
          signal: controller.signal,
        });
        if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
        const data = (await res.json()) as RawOsmResponse;
        if (!data || !Array.isArray(data.elements)) throw new Error('Malformed response');
        return data;
      } catch (err: any) {
        lastError = err instanceof Error ? err : new Error(String(err));
        console.log(
          `      attempt ${attempt}/3 on ${endpoint} failed (${err?.message || err}) — retrying in ${attempt * 5}s...`
        );
      } finally {
        clearTimeout(timeoutId);
      }
      await sleep(attempt * 5000);
    }
  }
  throw lastError || new Error('All Overpass mirrors failed.');
}

function polygonCentroid(poly: { x: number; z: number }[]): { x: number; z: number } {
  let sx = 0;
  let sz = 0;
  for (const p of poly) {
    sx += p.x;
    sz += p.z;
  }
  return { x: sx / poly.length, z: sz / poly.length };
}

interface HalfPlane {
  axis: 'x' | 'z';
  value: number;
  inside: (p: { x: number; z: number }) => boolean;
}

/**
 * Sutherland–Hodgman clip of a polygon against the square [-half, half]^2.
 * River strips fetched with `around:` extend beyond the map circle, so they are
 * trimmed to the terrain extent to avoid floating water over the void.
 */
export function clipPolygonToBounds(poly: { x: number; z: number }[], half: number): { x: number; z: number }[] {
  const planes: HalfPlane[] = [
    { axis: 'x', value: -half, inside: (p) => p.x >= -half },
    { axis: 'x', value: half, inside: (p) => p.x <= half },
    { axis: 'z', value: -half, inside: (p) => p.z >= -half },
    { axis: 'z', value: half, inside: (p) => p.z <= half },
  ];

  let current = poly;
  for (const plane of planes) {
    const next: { x: number; z: number }[] = [];
    for (let i = 0; i < current.length; i++) {
      const a = current[i];
      const b = current[(i + 1) % current.length];
      const aIn = plane.inside(a);
      const bIn = plane.inside(b);

      if (aIn && bIn) {
        next.push(b);
      } else if (aIn && !bIn) {
        next.push(intersect(a, b, plane));
      } else if (!aIn && bIn) {
        next.push(intersect(a, b, plane), b);
      }
    }
    current = next;
    if (current.length < 3) return [];
  }

  return current;
}

/** Intersect segment a->b with the half-plane boundary line. */
function intersect(
  a: { x: number; z: number },
  b: { x: number; z: number },
  plane: HalfPlane
): { x: number; z: number } {
  const delta = plane.axis === 'x' ? b.x - a.x : b.z - a.z;
  const t = Math.abs(delta) < 1e-12 ? 0 : (plane.value - (plane.axis === 'x' ? a.x : a.z)) / delta;
  const clamped = Math.min(1, Math.max(0, t));
  return { x: a.x + (b.x - a.x) * clamped, z: a.z + (b.z - a.z) * clamped };
}

function mergeWater(
  existing: LanduseArea[],
  incoming: LanduseArea[]
): { merged: LanduseArea[]; added: number; replaced: number; removed: number } {
  const CLIP_HALF = 4200; // just inside the terrain extent (radius * 2.2)
  const existingById = new Map<string, LanduseArea>();
  for (const l of existing) existingById.set(String(l.id), l);

  // Relation ids are `l_rel_<relid>_<n>` — the n differs between processing runs,
  // so match on the relation-id prefix instead.
  const relationPrefixToEntry = new Map<string, LanduseArea>();
  for (const l of existing) {
    const id = String(l.id);
    if (id.startsWith('l_rel_')) {
      relationPrefixToEntry.set(id.split('_').slice(0, 3).join('_'), l);
    }
  }
  const existingCentroids = existing
    .filter((l) => l.type === 'water')
    .map((l) => polygonCentroid(l.polygon));

  const merged = [...existing];
  const removeIds = new Set<string>();
  let added = 0;
  let replaced = 0;
  let removed = 0;

  for (const w of incoming) {
    if (w.type !== 'water' || !w.polygon || w.polygon.length < 3) continue;
    const clipped = clipPolygonToBounds(w.polygon, CLIP_HALF);

    const wId = String(w.id);
    const relKey = wId.startsWith('l_rel_') ? wId.split('_').slice(0, 3).join('_') : null;

    // Same OSM element already present (from a previous merge run or the original
    // fetch) -> replace its polygon with the clipped version instead of duplicating.
    const existingEntry =
      existingById.get(wId) ??
      (relKey ? relationPrefixToEntry.get(relKey) : undefined);
    if (existingEntry) {
      if (clipped.length >= 3) {
        existingEntry.polygon = clipped;
        if (w.name) existingEntry.name = w.name;
        replaced++;
      } else {
        // The OSM element sits entirely outside the map bounds (river relations
        // span the whole waterway) — drop the stale out-of-bounds copy.
        removeIds.add(String(existingEntry.id));
        removed++;
      }
      continue;
    }

    if (clipped.length < 3) continue;

    const c = polygonCentroid(clipped);
    const duplicate = existingCentroids.some((ec) => Math.hypot(ec.x - c.x, ec.z - c.z) < 3);
    if (duplicate) continue;

    merged.push({ ...w, polygon: clipped });
    existingById.set(wId, merged[merged.length - 1]);
    existingCentroids.push(c);
    added++;
  }

  const final = removeIds.size > 0 ? merged.filter((l) => !removeIds.has(String(l.id))) : merged;

  return { merged: final, added, replaced, removed };
}

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  let totalAdded = 0;

  // Optional `--only id1,id2` filter for retrying failed cities.
  const onlyIdx = process.argv.indexOf('--only');
  const onlySet =
    onlyIdx !== -1
      ? new Set(process.argv[onlyIdx + 1]?.split(',').map((s) => s.trim()).filter(Boolean))
      : null;

  for (const preset of LOCATION_PRESETS) {
    if (onlySet && !onlySet.has(preset.id)) continue;
    const target = path.join(OUT_DIR, `${preset.id}.json`);
    if (!fs.existsSync(target)) {
      console.log(`[${preset.id}] bundle missing, skipping.`);
      continue;
    }

    const existing = JSON.parse(fs.readFileSync(target, 'utf8'));
    if (!existing.elevation) {
      console.log(`[${preset.id}] no elevation in bundle, skipping.`);
      continue;
    }

    console.log(`[${preset.id}] ${preset.name} — fetching waterways...`);
    try {
      const raw = await fetchWater(preset.lat, preset.lon);
      const processed = processOsmData(
        raw,
        { lat: preset.lat, lon: preset.lon },
        RADIUS,
        'Water merge: Overpass waterway/water',
        existing.elevation
      );

      const incomingWater = processed.landuse.filter((l) => l.type === 'water');
      const { merged, added, replaced, removed } = mergeWater(existing.landuse || [], incomingWater);

      if (added > 0 || replaced > 0 || removed > 0) {
        existing.landuse = merged;
        fs.writeFileSync(target, JSON.stringify(existing));
        console.log(
          `   OK -> +${added} new, ${replaced} replaced/clipped, ${removed} removed OOB (${incomingWater.length} fetched), ` +
            `total water ${merged.filter((l) => l.type === 'water').length}`
        );
        totalAdded += added;
      } else {
        console.log(`   nothing new to add (${incomingWater.length} fetched, all duplicates).`);
      }
    } catch (e: any) {
      console.error(`   FAILED -> ${e?.message ?? e}`);
    }

    await sleep(5000);
  }

  console.log(`\nDone. Added ${totalAdded} water polygons across bundles.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
